apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-my-prometheus-alertmanager-0
spec:
  capacity:
    storage: 10Gi # Adjust based on Alertmanager's needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-my-prometheus-alertmanager-0
  local:
    path: /mnt/prometheus/alertmanager
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - eks-worker-2
