apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-prometheus-server # Name your PV accordingly
spec:
  capacity:
    storage: 10Gi # Ensure this meets or exceeds the PVC requirement
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-prometheus-server
  local:
    path: /mnt/prometheus/server # Ensure this directory exists on the specified node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - eks-worker-1 # Adjust to the target node's name
