apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-kustomize

bases:
  - ../../base

components:
  # - ../../components/auth
  # - ../../components/db/postgres
  # - ../../components/db/db-ui/pgadmin
  - ../../components/db/mongodb
  - ../../components/db/db-ui/mongo-express
