apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-study-deployment
  # namespace: core
spec:
  selector:
    matchLabels:
      app: nginx-study
  template:
    metadata:
      labels:
        app: nginx-study
    spec:
      securityContext:
        runAsUser: 0 # Specifies that the pod should run as root
      containers:
      - name: nginx-study
        image: nginx:latest
        ports:
        - containerPort: 80
