apiVersion: v1
kind: Service
metadata:
  name: nginx-study
  namespace: core
  labels:
    app: nginx-study
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # protocol: TCP
      # nodePort: 30733
  selector:
    app: nginx-study
