apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app: dashy-service
  name: dashy-service-configmap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashy-service
  name: dashy-service
  namespace: core
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dashy-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashy-service
  name: dasy-service-deployment
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy-service
  template:
    metadata:
      labels:
        app: dashy-service
    spec:
      containers:
      - image: lissy93/dashy:latest
        name: dashy-service
        ports:
        - containerPort: 80
      securityContext:
        runAsUser: 0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: dashy-service
  name: dashy-service
  namespace: core
spec:
  ingressClassName: nginx
  rules:
  - host: dashy.local.m-mobility.com
    http:
      paths:
      - backend:
          service:
            name: dashy-service
            port:
              number: 80
        path: /
        pathType: Prefix
