apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-service


resources:
- nginx-service-configMap.yaml
- nginx-service-deployment.yaml
- nginx-service-ingress.yaml
- nginx-service-svc.yaml
labels:
- includeSelectors: true
  pairs:
    app: nginx-service
