apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: core
spec:
  selector:
    app: nginx-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30733
  
