apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-study-deployment
  # namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-study
  template:
    metadata:
      labels:
        app: nginx-study
    spec:
      containers:
      - name: nginx-study
        image: nginx:latest
        ports:
        - containerPort: 80
