apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-service-configmap
  namespace: core  # Make sure this matches the namespace of your NGINX Ingress Controller
data:
  proxy-body-size: "100m"
  use-forwarded-headers: "true"

  oidc.config: |
    name: Keycloak
    issuer: http://10.0.0.143:32589/auth/realms/myrealm
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    redirectURI: https://10.0.0.143:30080/auth/callback

