apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd-service

resources:
- argocd-service-configmap.yaml
- argocd-service-ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app: argocd-server
