apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    component: keycloak
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 32589
  type: NodePort
