apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: core
type: Opaque
data:
  admin-username: YWRtaW4=  # base64 encoded value of 'admin'
  admin-password: YWRtaW4=  # base64 encoded value of 'admin'
