apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak

resources:
- keycloak-service-secretMap.yaml
# - keycloak-service-ingress.yaml
- keycloak-service-svc.yaml
- keycloak-service-deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app: keycloak
