apiVersion: v1
data:
  proxy-body-size: 100m
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  labels:
    app: argocd-server
  name: argocd-service-configmap
  namespace: core
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app: argocd-server
  name: argocd-server-ingress
  namespace: core
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.local.m-mobility.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /
        pathType: Prefix
