helm:
  parameters:
  - name: image.repository
    value: sebastine/project-tsukinome-release
    forcestring: false
  - name: service.port
    value: "8000"
    forcestring: false
  - name: image.tag
    value: v1.1.0
    forcestring: true
  - name: image.name
    value: sebastine/project-tsukinome-release
    forcestring: true
