apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy-service
  template:
    metadata:
      labels:
        app: dashy-service
    spec:
      containers:
      - name: dashy-service
        image: lissy93/dashy:latest
        ports:
        - containerPort: 80
