apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: mnmsw-k8s/applicationset/project
    repoURL: git@github.com:Sebastine-Atemnkeng/mnmsw-k8s.git
    targetRevision: main