apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: stag
          - env: pre-prod
          - env: prod
          - env: bugFix
  template:
    metadata:
      name: "apps-{{.env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: argocd-app-of-apps
      source:
        repoURL: git@github.com:Sebastine-Atemnkeng/mnmsw-k8s.git
        targetRevision: HEAD
        path: envs/{{.env}}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true