apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app: nginx-service
  name: nginx-service-configmap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-service
  name: nginx-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
      - image: nginx:latest
        name: nginx-service
        ports:
        - containerPort: 80
      securityContext:
        runAsUser: 0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  labels:
    app: nginx-service
  name: nginx-service
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-service.com
    http:
      paths:
      - backend:
          service:
            name: nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix
