apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres

resources:
- postgresql-statefulset.yaml
- postgresql-pv-pvc.yaml
- postgresql-secretMap.yaml
- postgresql-svc.yaml

labels:
- includeSelectors: true
  pairs:
    app: postgres
