apiVersion: v1
data:
  admin-password: YWRtaW4=
  admin-username: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: keycloak
  name: keycloak-secret
  namespace: core
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: core
spec:
  ports:
  - name: http
    nodePort: 8080
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - args:
        - start-dev
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              key: admin-username
              name: keycloak-secret
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: keycloak-secret
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:24.0.1
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
