apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins-service

resources:
- jenkins-service-configMap.yaml
- jenkins-service-deployment.yaml
- jenkins-service-ingress.yaml
- jenkins-service-svc.yaml
labels:
- includeSelectors: true
  pairs:
    app: jenkins-service
